colorScheme = "forest"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "projects" ]
firebase = { }
fathomAnalytics = { }
verification = { }

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "wave.svg"
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/projects"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = false
showSummary = true
sharingLinks = [
  "linkedin",
  "twitter",
  "whatsapp",
  "pinterest",
  "reddit",
  "facebook",
  "email"
]
showZenMode = false

[list]
showHero = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
